# Generated by Django 4.2.5 on 2023-10-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_control_delete_led'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='image',
            field=models.ImageField(blank=True, default='control.png', null=True, upload_to='control'),
        ),
    ]
