# Generated by Django 4.2.5 on 2023-10-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='connection_status',
            field=models.BooleanField(default=False),
        ),
    ]
