# Generated by Django 4.2.5 on 2023-10-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_config_connection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='passport.jpg', upload_to='passport'),
        ),
    ]
