# Generated by Django 4.2.5 on 2023-10-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_user_threat_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disable_reason',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
