# Generated by Django 4.2.5 on 2023-10-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_user_disable_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='acknowledge_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='control',
            name='acknowledge_response',
            field=models.BooleanField(default=False),
        ),
    ]
