# Generated by Django 4.2.5 on 2023-10-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_config_acknowledge_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='acknowledge_request',
            field=models.BooleanField(default=True),
        ),
    ]
