# Generated by Django 4.2.5 on 2023-10-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_config_acknowledge_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='connection_status',
            field=models.BooleanField(default=False),
        ),
    ]
